version: "3"

services:
  app:
    build:
      context: .
      args:
        - ENVIRONMENT=local
    ports:
      - "8000:8000"
    entrypoint: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    env_file:
      - .env-db
      - .env-django
    volumes:
      - .:/usr/src/app
    depends_on: 
      - db
  
  # app-test:
  #   build:
  #     context: .
  #     args:
  #       - ENVIRONMENT=test
  #   ports:
  #     - "8090:8090"
  #   entrypoint: ["python", "manage.py", "runserver", "0.0.0.0:8090"]
  #   env_file:
  #     - .env-db
  #     - .env-django
  #   volumes:
  #     - .:/usr/src/app
  #   depends_on: 
  #     - db

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env-pgadmin
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env-db
    volumes:
      - pgdb:/var/lib/postgresql/data

volumes:
  pgdb: