# Generated by Django 4.1.7 on 2023-05-10 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('type', models.CharField(max_length=15, verbose_name='Operation type')),
                ('cost', models.IntegerField(verbose_name='Operation cost')),
            ],
            options={
                'verbose_name': 'Operation',
                'verbose_name_plural': 'Operations',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('user_balance', models.IntegerField(verbose_name='User balance')),
                ('operation_response', models.CharField(max_length=15, verbose_name='Operation Response')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.operation')),
            ],
            options={
                'verbose_name': 'Record',
                'verbose_name_plural': 'Records',
            },
        ),
    ]
